name: COBOL Check Automation

on:
  push:
    branches: [ main ]

jobs:
  cobol-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5
        with: 
          submodules: true
          lfs: true  
      - name: set up Java
        uses: actions/setup-java@v5
        with:
          java-version: '25'
          distribution: 'temurin' # Add this 
      - name: Show Java version
        run: java -version
      - name: Create directory and copy files
        run: |
          mkdir -p cobcheck
          cp -r cob-check/* cobcheck/
          ls -lR cobcheck/ # Verify copy

      - name: Set up Mainframe Environment and upload COBOL Check
        env:
          ZOWE_USERNAME: ${{ secrets.ZOWE_USERNAME }}
          ZOWE_PASSWORD: ${{ secrets.ZOWE_PASSWORD }}
        run: |
          chmod +x .github/scripts/mainframe_operations.sh
          .github/scripts/mainframe_operations.sh
      - name: Run COBOL Check on Mainframe
        env:
          ZOWE_USERNAME: ${{ secrets.ZOWE_USERNAME }}
          ZOWE_PASSWORD: ${{ secrets.ZOWE_PASSWORD }}
        run: |
          chmod +x .github/scripts/mainframe_operations.sh
          .github/scripts/mainframe_operations.sh
  
  # 1. Ensure Node.js is installed
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'

      # 2. Install Zowe CLI globally
      - name: Install Zowe CLI
        run: npm install -g @zowe/cli@latest

      
          
        
     

