name: COBOL Check Automation

on:
  push:
    branches: [ main ]

jobs:
  cobol-check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      - name: set up Java
        uses: actions/setup-java@v5
        with:
          java-version: '25'
      - name: Setup Mainframe Environment and upload COBOL Check
        env:
          ZOWE_USERNAME: ${{secrets.ZOWE_USERNAME}}
          ZOWE_PASSWORD: ${{secrets.ZOWE_PASSWORD}}
        run: |
          # Here we will add our commands to run cobolcheck
          # echo "Running COBOL Check"
          # Add actual cobolcheck commands here
          chmod +x .github/scripts/zowe_operations.sh
          .github/scripts/zowe_operations.sh
      - name: Run COBOL Check on Mainframe
        env:
          ZOWE_USERNAME: ${{ secrets.ZOWE_USERNAME }}
          ZOWE_PASSWORD: ${{ secrets.ZOWE_PASSWORD }}
        run: |
          chmod +x .github/scripts/mainframe_operations.sh
          .github/scripts/mainframe_operations.sh    
      - name: Set up JDK
        uses: actions/setup-java@v5 # Or @v2, @v3
        with:
          java-version: '25'
          distribution: 'temurin' # Add this 
          check-latest: true

